version: "3.8"

services:
  ctlog:
    build:
      dockerfile: ./.ci/ctlog.Dockerfile
      context: .
    container_name: ctlog
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - inner

networks:
  inner:
#   project2:
#     build:
#       context: ./apps/project2
#     ports:
#       - "3001:3001"
#     environment:
#       - NODE_ENV=production
